site_name: Warren的个人小站
site_description: 欲买桂花同载酒，终不似少年游
theme:
  name: material
  font: 
    text: Noto Serif SC
  palette: 
    primary: cyan
    accent: red
  icon:
    logo: material/ski
    repo: fontawesome/brands/github
    previous: fontawesome/solid/angle-left
    top: fontawesome/solid/angles-up
    alternate: fontawesome/solid/language
  features:
    - navigation.tabs
    #- navigation.expand
    - navigation.top
repo_url: https://github.com/Warrenzju/Warrenzju.github.io
repo_name: Warrenzju.github.io
nav:
  - Home: 
    - Me: index.md
    - Markdown基本语法: home/Markdown语法.md
  - Course Notes:
    - 电磁场与电磁波:
      - Chapter3: course notes/EM/chapter3.md
      - Chapter4、5: course notes/EM/Emchapter41.md
      - Chapter6: course notes/EM/Emchapter61.md
      - Chapter7: course notes/EM/Emchapter7.md
      - revise fot all 7 chapter: course notes/EM/Emrevise.md
      - Chapter8: course notes/EM/Emchapter8.md
    - 马克思主义原理: course notes/mayuan.md
    - 模电:
      - 三极管总结: course notes/modian/sanjiguan.md
      - 单管放大电路总结: course notes/modian/danguanfangdadianlu.md
      - 负反馈总结: course notes/modian/fufankui.md
    - 偏微分: course notes/pde/pde.md
    - 应用光学: 
      - chapter1、2: course notes/opt/chapter1and2.md
      - chapter3: course notes/opt/optchapter3.md
      - chapter4: course notes/opt/Optchapter4.md
      - chapter5: course notes/opt/Optchapter5.md
      - chapter6: course notes/opt/Optchapter6.md
      - Chapter7: course notes/opt/chapter7.md
      - chapter12: course notes/opt/Optchapter12.md
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - attr_list
  - admonition
  - footnotes
  # - callouts
  - md_in_html
  - markdown.extensions.abbr # 支持Markdown文件上方自定义标题标签等
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
extra_javascript:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - mkdocs/javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  #- mkdocs/javascripts/mathjax.js
  #- https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - https://unpkg.com/katex@0/dist/katex.min.css
  # [自定义 css]
  # 不使用底部的翻页
  - mkdocs/css/no-footer.css
  # 无序列表符号自定义
  - mkdocs/css/unordered-list-symbols.css
  - mkdocs/css/Rounded corners.css
extra:
  homepage:  https://warrenzju.github.io/
